import { Router } from "express";
import { getProvider } from "../ai/provider.js";
import db from "../db/database.js";
import { createHash } from "crypto";

const router = Router();

function hashQuestion(question) {
  return createHash("sha256").update(question.toLowerCase().trim()).digest("hex").slice(0, 16);
}

function findSimilarAnswers(question) {
  const hash = hashQuestion(question);
  return db.prepare("SELECT * FROM answer_memory WHERE question_hash = ? ORDER BY used_count DESC LIMIT 3").all(hash);
}

function saveAnswer(question, answer, context) {
  const hash = hashQuestion(question);
  const existing = db.prepare("SELECT id FROM answer_memory WHERE question_hash = ?").get(hash);
  if (existing) {
    db.prepare("UPDATE answer_memory SET used_count = used_count + 1, answer = ? WHERE question_hash = ?").run(answer, hash);
  } else {
    db.prepare(`INSERT INTO answer_memory (id, question_hash, question, answer, context, created_at)
      VALUES (?, ?, ?, ?, ?, ?)`).run(
      crypto.randomUUID(),
      hash,
      question,
      answer,
      JSON.stringify(context || {}),
      new Date().toISOString()
    );
  }
}

// POST /api/analyze
// Processes AI-required fields — called from background worker
router.post("/", async (req, res) => {
  const { fields, profile, jobDescription } = req.body;

  if (!fields || !Array.isArray(fields)) {
    return res.status(400).json({ error: "fields array required" });
  }

  const provider = await getProvider();
  const results = [];

  for (const field of fields) {
    const question = field.label || field.ariaLabel || field.placeholder || field.name;
    if (!question) {
      results.push({ fieldId: field.id, status: "needs_input", value: "", source: "no_question" });
      continue;
    }

    // check answer memory
    const similar = findSimilarAnswers(question);
    const previousAnswers = similar.map((s) => s.answer);

    if (!provider) {
      results.push({
        fieldId: field.id,
        status: "needs_input",
        value: "",
        source: "ai_unavailable",
        needsUserInput: true,
        userPrompt: `AI unavailable. Please answer: "${question}"`,
      });
      continue;
    }

    try {
      const answer = await provider.generateAnswer(question, {
        profile,
        jobDescription,
        previousAnswers,
      });

      // save to memory
      saveAnswer(question, answer, { jobDescription: jobDescription?.slice(0, 200) });

      results.push({
        fieldId: field.id,
        status: "ai",
        value: answer,
        source: "ai_generated",
        confidence: 0.75,
        reasoning: `Generated by AI${similar.length ? ` (${similar.length} similar previous answers used as context)` : ""}`,
      });
    } catch (err) {
      results.push({
        fieldId: field.id,
        status: "needs_input",
        value: "",
        source: "ai_error",
        needsUserInput: true,
        userPrompt: `AI failed. Please answer: "${question}"`,
      });
    }
  }

  res.json({ results });
});

export default router;
